---
name: date2iso-composed
project: date2iso
program: allennlp
method: grid
command:
  - ${program}
  - "train-with-wandb"
  - "configurations/composed__wandb.jsonnet"
  - "--include-package=library"
  - "--include-package=allennlp_models"
  - ${args}
metric:
  name: validation/sequence_accuracy
  goal: maximize
parameters:
  model.encoder.num_layers:
    values:
      - 1
      - 2
  env.hidden_size:
    values:
      - 50
      - 70
      - 100
  env.embedding_dim:
    values:
      - 10
      - 30
      - 50
  data_loader.batch_size:
    values:
      - 128
      - 512
  trainer.cuda_device:
    value: 0
